//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clima.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Api : global::System.Configuration.ApplicationSettingsBase {
        
        private static Api defaultInstance = ((Api)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Api())));
        
        public static Api Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.105:8088")]
        public string ipVmix {
            get {
                return ((string)(this["ipVmix"]));
            }
            set {
                this["ipVmix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cidades.gtzip")]
        public string gcInput {
            get {
                return ((string)(this["gcInput"]));
            }
            set {
                this["gcInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Tempo\\Icon\\")]
        public string directImagem {
            get {
                return ((string)(this["directImagem"]));
            }
            set {
                this["directImagem"] = value;
            }
        }
    }
}
