//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clima.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class AppConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppConfiguration defaultInstance = ((AppConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppConfiguration())));
        
        public static AppConfiguration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1038/caxias-ma</string>
  <string>94/saoluis-ma</string>
  <string>93/imperatriz-ma</string>
  <string>1035/bacabal-ma</string>
  <string>1034/acailandia-ma</string>
  <string>6580/afonsocunha-ma</string>
  <string>6581/aldeiasaltas-ma</string>
  <string>1041/coelhoneto-ma</string>
  <string>1040/codo-ma</string>
  <string>6594/saojoaodosoter-ma</string>
  <string>1036/balsas-ma</string>
  <string>1043/coroata-ma</string>
  <string>1052/pedreiras-ma</string>
  <string>1056/presidentedutra-ma</string>
  <string>1067/timon-ma</string>
  <string>1060/santaines-ma</string>
  <string>91/barradocorda-ma</string>
  <string>1068/tuntum-ma</string>
  <string>1052/pedreiras-ma</string>
  <string>5320/matoes-ma</string>
  <string>6000/timbiras-ma</string>
  <string>5980/peritoro-ma</string>
  <string>5186/axixa-ma</string>
  <string>6583/duquebacelar-ma</string>
  <string>1045/grajau-ma</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection comboUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["comboUrl"]));
            }
            set {
                this["comboUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1038/caxias-ma</string>
  <string>94/saoluis-ma</string>
  <string>93/imperatriz-ma</string>
  <string>5982/pioxii-ma</string>
  <string>1035/bacabal-ma</string>
  <string>1034/acailandia-ma</string>
  <string>6580/afonsocunha-ma</string>
  <string>6581/aldeiasaltas-ma</string>
  <string>1041/coelhoneto-ma</string>
  <string>1040/codo-ma</string>
  <string>6594/saojoaodosoter-ma</string>
  <string>1036/balsas-ma</string>
  <string>1043/coroata-ma</string>
  <string>1052/pedreiras-ma</string>
  <string>1056/presidentedutra-ma</string>
  <string>1067/timon-ma</string>
  <string>1060/santaines-ma</string>
  <string>91/barradocorda-ma</string>
  <string>1068/tuntum-ma</string>
  <string>1052/pedreiras-ma</string>
  <string>5320/matoes-ma</string>
  <string>6000/timbiras-ma</string>
  <string>5980/peritoro-ma</string>
  <string>5186/axixa-ma</string>
  <string>6583/duquebacelar-ma</string>
  <string>1045/grajau-ma</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection listaCidades {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["listaCidades"]));
            }
            set {
                this["listaCidades"] = value;
            }
        }
    }
}
