//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clima.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Xpath : global::System.Configuration.ApplicationSettingsBase {
        
        private static Xpath defaultInstance = ((Xpath)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Xpath())));
        
        public static Xpath Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div[3]/div[6]/div[3]/div[1]/div[2]/div[1]/div/span/text()")]
        public string nome {
            get {
                return ((string)(this["nome"]));
            }
            set {
                this["nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div[3]/div[6]/div[3]/div[1]/div[2]/div[2]/div[2]/div[1]/ul/li[2]/div/s" +
            "pan")]
        public string indice {
            get {
                return ((string)(this["indice"]));
            }
            set {
                this["indice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("min-temp-1")]
        public string min {
            get {
                return ((string)(this["min"]));
            }
            set {
                this["min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("max-temp-1")]
        public string max {
            get {
                return ((string)(this["max"]));
            }
            set {
                this["max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div[3]/div[6]/div[3]/div[1]/div[2]/div[2]/div[2]/div[1]/ul/li[4]/div/s" +
            "pan[2]")]
        public string umdMin {
            get {
                return ((string)(this["umdMin"]));
            }
            set {
                this["umdMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div[3]/div[6]/div[3]/div[1]/div[2]/div[2]/div[2]/div[1]/ul/li[4]/div/s" +
            "pan[4]")]
        public string umdMax {
            get {
                return ((string)(this["umdMax"]));
            }
            set {
                this["umdMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div[3]/div[6]/div[3]/div[1]/div[2]/div[2]/div[2]/div[1]/ul/li[3]/div")]
        public string vento {
            get {
                return ((string)(this["vento"]));
            }
            set {
                this["vento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div[3]/div[6]/div[3]/div[1]/div[2]/div[2]/div[1]/div[1]/p")]
        public string status {
            get {
                return ((string)(this["status"]));
            }
            set {
                this["status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-font-base -light")]
        public string nomeAgora {
            get {
                return ((string)(this["nomeAgora"]));
            }
            set {
                this["nomeAgora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-bold -gray-dark-2 -font-55 _margin-l-20 _center")]
        public string tempoAgora {
            get {
                return ((string)(this["tempoAgora"]));
            }
            set {
                this["tempoAgora"] = value;
            }
        }
    }
}
